import Head from "next/head";
import { useRouter } from "next/router";
import { HomeLink } from "~/features/home/components/HomeLink";
import Loader from "~/components/Loader";

import { api } from "~/utils/api";
import Layout from "~/components/Layouts/Layout";

export default function Home() {
  const router = useRouter();
  const { error, isPending } = api.auth.check.useQuery();

  if (error?.data?.code === "UNAUTHORIZED") {
    void router.push("/login");
  }

  if (isPending) {
    return (
      <>
        <Head>
          <title>SI KOP BANGKIT</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="grid min-h-screen w-full place-content-center gap-8 bg-slate-800 text-center">
          <Loader className="h-24 w-24" />
        </div>
      </>
    );
  }

  return (
    <Layout page="Beranda">
      <section className="flex w-full flex-1 flex-col items-center justify-center bg-slate-800">
        <h1 className="text-center text-3xl text-white">
          SISTEM CEK TAGIHAN KOPERASI BANGKIT BERSAMA
        </h1>
        <div className="mt-4 flex flex-col items-center sm:flex-row">
          <HomeLink href={"/anggota"}>Anggota</HomeLink>
          <HomeLink href={"/instansi"}>Instansi</HomeLink>
          <HomeLink href={"/mutasi"}>Mutasi</HomeLink>
          <HomeLink href={"/tagihan"}>Tagihan</HomeLink>
        </div>
      </section>
    </Layout>
  );
}
