import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, type ComponentType } from "react";
import Loader from "~/components/Loader";
import { api } from "~/utils/api";

const withAuth = <P extends object>(WrappedComponent: ComponentType<P>) => {
  const AuthedComponent = (props: P) => {
    const router = useRouter();
    const { mutate, isPending } = api.auth.check.useMutation({
      onError: async (error) => {
        if (error.data?.code === "UNAUTHORIZED") {
          await router.push("/login");
        }
      },
    });

    useEffect(() => {
      mutate();
    }, [mutate]);

    if (isPending) {
      return (
        <>
          <Head>
            <title>SI KOP BANGKIT</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="grid min-h-screen w-full place-content-center gap-8 bg-slate-800 text-center">
            <Loader className="h-24 w-24" />
          </div>
        </>
      );
    }

    return <WrappedComponent {...props} />;
  };

  return AuthedComponent;
};

export default withAuth;
