import { type GetServerSideProps } from "next";
import Head from "next/head";
import { type ReactNode } from "react";
import { ToastContainer } from "react-toastify";
import { verifyToken } from "~/utils/jwt";
import InstansiDatalist from "../InstansiDatalist";
import Navbar from "./Navbar";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const access_token = ctx.req.cookies.access_token;

  if (!access_token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  try {
    verifyToken(access_token);
    return { props: {} };
  } catch (err) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
};

type LayoutPropsType = {
  title?: string;
  page?: string;
  children?: string | ReactNode;
};

const Layout = ({ title, page, children }: LayoutPropsType) => {
  return (
    <>
      <Head>
        <title>
          {page ? `SI KOP BANGKIT | ${page}` : title ? title : "SI KOP BANGKIT"}
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-[calc(100vh_-_76px)] flex-col bg-slate-800 px-4 pb-8 pt-8 text-white lg:px-16">
        {children}
      </main>
      <footer className="flex w-full flex-col gap-1 bg-slate-800 pb-14 pt-8 text-center text-slate-600">
        <span>
          &copy; {new Date().getFullYear()} - Koperasi Bangkit Bersama
          Banyuwangi
        </span>
        <span>Made by Fata Nabil Fikri 😎</span>
      </footer>
      <div id="agency-datalist-wrapper">
        <InstansiDatalist />
      </div>
      <ToastContainer
        position="bottom-right"
        hideProgressBar={true}
        newestOnTop
        autoClose={5000}
        closeButton={false}
      />
    </>
  );
};

export default Layout;
